# Generated by Django 4.2.4 on 2023-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email_of_future_contact',
            field=models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email For Future Contact'),
        ),
        migrations.AlterField(
            model_name='licensor',
            name='email_of_future_contact',
            field=models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email For Future Contact'),
        ),
    ]
