# Generated by Django 4.2.4 on 2023-08-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agent_email_of_future_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paralegal',
            name='zip_postal_code',
        ),
    ]
