# Generated by Django 4.2.4 on 2024-07-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_otherprovider_address_line_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventor',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
    ]
