# Generated by Django 4.2.4 on 2024-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_inventor_is_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensor',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Prof', 'Prof'), ('Dr', 'Dr')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='licensor',
            name='type_of_contract',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Contractor', 'Contractor'), ('Secondment', 'Secondment'), ('Licensor', 'Licensor')], max_length=12, null=True),
        ),
    ]
