# Generated by Django 4.2.4 on 2023-08-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_licensor_zip_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='zip_postal_code',
        ),
    ]
