# Generated by Django 4.2.4 on 2024-07-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_licensor_title_alter_licensor_type_of_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherprovider',
            name='contact_person',
            field=models.CharField(default=1, max_length=128, verbose_name='Contact Person(s)'),
            preserve_default=False,
        ),
    ]
