# Generated by Django 4.2.4 on 2023-08-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_attorney_zip_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='zip_postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Zip/Postal Code'),
        ),
    ]
