# Generated by Django 4.2.4 on 2024-08-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_otherprovider_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer_instructions',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
