# Generated by Django 4.2.4 on 2024-08-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contact_customer_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=2, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
