# Generated by Django 4.2.4 on 2024-09-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_familynumbercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademark',
            name='trademark_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Trademark Name'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='type_of_trademark',
            field=models.CharField(blank=True, choices=[('Device marks', 'Device marks'), ('Service marks', 'Service marks'), ('Collective marks', 'Collective marks'), ('Certification marks', 'Certification marks'), ('Well-known marks', 'Well-known marks'), ('Unconventional trademarks', 'Unconventional trademarks')], max_length=128, null=True, verbose_name='Type of Trademark'),
        ),
    ]
