# Generated by Django 4.2.4 on 2024-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_trademark_trademark_name_trademark_type_of_trademark'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademark',
            name='applicaation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Application date'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Tax Date'),
        ),
    ]
