# Generated by Django 4.2.4 on 2023-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_agent_email_of_future_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventor',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Prof', 'Prof'), ('Dr', 'Dr')], max_length=12, null=True),
        ),
    ]
