# Generated by Django 4.2.4 on 2024-09-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_costcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Inventor', 'Inventor'), ('Applicant', 'Applicant'), ('Licensor', 'Licensor'), ('Licensee', 'Licensee'), ('Consultant', 'Consultant'), ('Associate', 'Associate'), ('Paralegal', 'Paralegal'), ('Attorney', 'Attorney'), ('OtherProvider', 'OtherProvider'), ('CostCenter', 'CostCenter')], max_length=16),
        ),
        migrations.AlterField(
            model_name='design',
            name='sub_filing_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Sub Filing Type'),
        ),
        migrations.AlterField(
            model_name='family',
            name='sub_filing',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Sub Filing'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='sub_filing_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Sub-Filing Type'),
        ),
    ]
