# Generated by Django 4.2.4 on 2023-08-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_inventor_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='zip_postal_code',
        ),
    ]
