# Generated by Django 4.2.4 on 2024-09-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_contact_type_alter_design_sub_filing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Filed', 'Filed'), ('Allowed', 'Allowed'), ('Granted(Live)', 'Granted(Live)'), ('Abandoned', 'Abandoned'), ('Granted(DEA)', 'Granted(DEA)'), ('Converted', 'Converted'), ('Expired', 'Expired'), ('Published', 'Published'), ('Registered', 'Registered')], max_length=128, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Filed', 'Filed'), ('Abandoned', 'Abandoned'), ('Sold', 'Sold'), ('Licensed', 'Licensed'), ('On Hold', 'On Hold'), ('Opposed', 'Opposed'), ('Registered', 'Registered')], max_length=128, null=True, verbose_name='Status'),
        ),
    ]
