# Generated by Django 4.2.4 on 2023-08-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_applicant_zip_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='zip_postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Zip/Postal Code'),
        ),
    ]
