# Generated by Django 4.2.4 on 2024-09-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_design_status_alter_family_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='case_office',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Case Office'),
        ),
        migrations.AddField(
            model_name='design',
            name='filing_type',
            field=models.CharField(blank=True, default='Patent', max_length=128, null=True, verbose_name='Filing type'),
        ),
        migrations.AddField(
            model_name='patent',
            name='filing_type',
            field=models.CharField(blank=True, default='Patent', max_length=128, null=True, verbose_name='Filing type'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='classes',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')], null=True, verbose_name='Classes'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='filing_type',
            field=models.CharField(blank=True, default='Patent', max_length=128, null=True, verbose_name='Filing type'),
        ),
    ]
