# Generated by Django 4.2.4 on 2023-08-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_applicant_zip_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
