# Generated by Django 4.2.4 on 2024-09-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_trademark_filing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes'),
        ),
    ]
