# Generated by Django 4.2.4 on 2023-08-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_patent_internal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='inventor',
            field=models.ManyToManyField(to='app.inventor'),
        ),
    ]
