# Generated by Django 4.2.4 on 2023-08-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_family_inventor'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='applicant',
            field=models.ManyToManyField(to='app.applicant'),
        ),
    ]
