# Generated by Django 4.2.4 on 2024-09-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_design_notes_alter_trademark_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='case_type',
            field=models.CharField(blank=True, choices=[('Draft Patent Application', 'Draft Patent Application'), ('Priority Application', 'Priority Application'), ('Provisional Application', 'Provisional Application'), ('Patent Application', 'Patent Application'), ('Divisional Application', 'Divisional Application'), ('PCT', 'PCT'), ('EP national', 'EP national')], max_length=128, null=True, verbose_name='Case Type'),
        ),
    ]
