# Generated by Django 4.2.4 on 2023-08-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_family_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='applicant',
            field=models.ManyToManyField(blank=True, null=True, to='app.applicant'),
        ),
        migrations.AlterField(
            model_name='family',
            name='inventor',
            field=models.ManyToManyField(blank=True, null=True, to='app.inventor'),
        ),
    ]
