# Generated by Django 4.2.4 on 2024-10-01 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_company_user_phone_alter_patent_case_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventiondisclosure',
            old_name='is_there_an_agreement',
            new_name='agreement',
        ),
        migrations.RemoveField(
            model_name='inventiondisclosure',
            name='id_ref_number',
        ),
        migrations.RemoveField(
            model_name='inventiondisclosure',
            name='primary_attorney',
        ),
        migrations.RemoveField(
            model_name='inventiondisclosure',
            name='secondary_attorney',
        ),
        migrations.AddField(
            model_name='inventiondisclosure',
            name='ID Reference',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='inventiondisclosure',
            name='attorney_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attorney_1_set', to='app.attorney'),
        ),
        migrations.AddField(
            model_name='inventiondisclosure',
            name='attorney_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attorney_2_set', to='app.attorney'),
        ),
    ]
