# Generated by Django 4.2.4 on 2024-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_is_there_an_agreement_inventiondisclosure_agreement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventiondisclosure',
            old_name='primary_paralegal',
            new_name='Paralegal 1',
        ),
        migrations.RenameField(
            model_name='inventiondisclosure',
            old_name='secondary_paralegal',
            new_name='Paralegal 2',
        ),
        migrations.RenameField(
            model_name='inventiondisclosure',
            old_name='ID Reference',
            new_name='Reference ID',
        ),
        migrations.AlterField(
            model_name='inventiondisclosure',
            name='proposed_inventors',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
