# Generated by Django 4.2.4 on 2024-10-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_primary_paralegal_inventiondisclosure_paralegal_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventiondisclosure',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invention_cost_centre', to='app.costcenter'),
        ),
        migrations.AlterField(
            model_name='inventiondisclosure',
            name='cost_centre_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invention_cost_centre_code', to='app.costcenter'),
        ),
    ]
