# Generated by Django 4.2.4 on 2024-10-04 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_inventiondisclosure_paralegal_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventiondisclosure',
            name='joint_venture_with_whom',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Joint Venture With Whom'),
        ),
        migrations.AlterField(
            model_name='inventiondisclosure',
            name='approval_or_rejection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approval/Rejection Date'),
        ),
        migrations.AlterField(
            model_name='inventiondisclosure',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contact', verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='inventiondisclosure',
            name='primary_paralegal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_paralegal_set', to='app.paralegal', verbose_name='Paralegal 1'),
        ),
        migrations.AlterField(
            model_name='inventiondisclosure',
            name='reasons_of_approval_or_rejection',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Reasons of Approval/Rejection'),
        ),
        migrations.AlterField(
            model_name='inventiondisclosure',
            name='secondary_paralegal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_paralegal_set', to='app.paralegal', verbose_name='Paralegal 2'),
        ),
    ]
