# Generated by Django 4.2.4 on 2024-10-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_inventiondisclosure_joint_venture_with_whom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventiondisclosure",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.contact",
                verbose_name="Approved/Rejected By",
            ),
        ),
        migrations.AlterField(
            model_name="inventiondisclosure",
            name="approved_for_filing",
            field=models.CharField(
                choices=[("Accepted", "Accepted"), ("Rejected", "Rejected")],
                max_length=8,
                verbose_name="Approved/Rejected for Filing",
            ),
        ),
    ]
