# Generated by Django 4.2.4 on 2024-11-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_inventiondisclosure_id_ref_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='application_date',
            field=models.DateField(blank=True, null=True, verbose_name='National App Date'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='associate_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_associate_ref_set', to='app.associate', verbose_name='Associate Ref'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='primary_attorney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_primary_attorney_set', to='app.attorney', verbose_name='Attorney 1'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='primary_paralegal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_primary_set', to='app.paralegal', verbose_name='Paralegal 1'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='secondary_attorney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_secondary_attorney_set', to='app.attorney', verbose_name='Attorney 2'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='secondary_paralegal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_secondary_set', to='app.paralegal', verbose_name='Paralegal 2'),
        ),
    ]
