# Generated by Django 4.2.4 on 2024-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_patent_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='official_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Official Number'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='priority_provisional_date',
            field=models.DateField(blank=True, max_length=128, null=True, verbose_name='Priority/Provisional Date'),
        ),
    ]
